spring.application.name: task-tracker

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5433/task_tracker"
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true